### ISSUE TITLE
"中文编程"知乎专栏开通!

### ISSUE THREAD

**Issue by nobodxbodon** [program-in-chinese/overview#48]
@program-in-chinese/all 特此通知: [地址](https://zhuanlan.zhihu.com/c_140193266)
首次创建专栏, 希望各位有经验的多指点. 初步打算把之前写的[一些文章](https://www.zhihu.com/people/wu-xuan-81-42/posts)选取一些发到专栏中. ~~另外, 不知专栏是否允许多人管理?~~ 在此也诚征编辑(能管理投稿, 调整作者权限, 发布文章)和作者(能发布文章).

下面是一些打算写的具体主题(不分先后), 希望坑都能填平:
- [x] 中文命名实践的阻力分析和对策: 基于https://github.com/program-in-chinese/overview/issues/18
- [x] 中文编程语言和开发环境需要的特性: 基于https://github.com/program-in-chinese/overview/issues/11 - [通用型的中文编程语言探讨之一: 高考](https://zhuanlan.zhihu.com/p/32677451)
- [ ] 中文编程不是什么: 有些误区也许需要澄清, 如-中文编程能实现自然语言编程(新手能够不需学习语法就像说话一样实现编程等等), 大多数软件工程的经验教训也适用于中文编程(如语言工具不是silver bullet, 项目管理/实施过程/开发方法是很大程度绝对项目成败的)等等
- [ ] 中文命名相关实践
  - [ ] Python [Django](https://github.com/program-in-chinese/Django_tutorial_zh)
  - [ ] JavaScript [React](https://zh-hans.reactjs.org/tutorial/tutorial.html)
  - [ ] google [protocol buffers](https://developers.google.com/protocol-buffers/)
- [x] Java快速入门教程(中文示例代码): 基于[短时间Java上手-中文代码版](https://github.com/program-in-chinese/java_in_hours_chn). 
- [ ] 其他语言的入门教程(中文示例代码)[Kotlin](https://github.com/program-in-chinese/kotlin_in_hours_chn), [JavaScript](https://github.com/program-in-chinese/javascript-in-a-day-chn),等等
- [ ] 新建IDE中的项目模板, 源自 https://github.com/program-in-chinese/overview/issues/11#issuecomment-417743692
- [ ] 中文编程语言的介绍
  - [x] [Z语言](https://github.com/TKT2016/ZLanguage3)
    - [x] [ZLOGO](https://zhuanlan.zhihu.com/p/31620122)
- [x] 在基于Spring的应用中使用中文命名: 基于[进销存示例](https://github.com/program-in-chinese/jinxiaocun)
- [ ] 对现有语言汉化的技术和心得 
  - [ ] [周蟒](https://github.com/gasolin/zhpy)和[中蟒](http://www.chinesepython.org/)采用的关键词和API汉化用词规整, 结合[关键字汉化讨论](https://github.com/program-in-chinese/overview/issues/40)。继续[周蟒3.0](https://github.com/gasolin/zhpy/issues/38)
  - [ ] [CTS](https://github.com/program-in-chinese/CTS)
  - [ ] [拼音输入法vscode插件](https://github.com/program-in-chinese/CTS_Typewriting)
  - [x] [cnlang](https://github.com/program-in-chinese/cnlang) [cnpython](https://github.com/swizl/cnpython)  gcc 多谢@swizl投稿这三个主题!
- [x] 从零开始开发一个(高级)语言/编程环境(教程, 用中文代码): 源自https://github.com/program-in-chinese/overview/issues/33
- [x] 从零开始实现一个汇编编译器(用中文代码): 基于[汇编编译器原型](https://github.com/program-in-chinese/assembler-in-chinese-experiment) - [烂尾工程: Java实现的汇编语言编译器](https://zhuanlan.zhihu.com/p/32607169)
- [x] 编码导致的乱码问题: 基于[部分中文出现乱码](https://github.com/program-in-chinese/team_website/blob/master/docs/_posts/2017-10-10-%E9%83%A8%E5%88%86%E4%B8%AD%E6%96%87%E5%87%BA%E7%8E%B0%E4%B9%B1%E7%A0%81.markdown)
- [ ] 对现有开源项目的汉化
  - [ ] [日语编程语言"抚子"](https://zhuanlan.zhihu.com/p/32273857)
  - [ ] [浏览器爬虫](https://github.com/nobodxbodon/ChromeCrawlerWildSpider)
  - [ ] [Rem编程语言](https://github.com/thautwarm/Rem/blob/ebnfparser2.0/tests-example_source_codes/chinese.rem)
  - [ ] 期待中的[miniasm](http://tieba.baidu.com/p/5095251226?pid=121222543812#121222543812), 已开源在[此](https://github.com/woodgreat/miniasm_release)
- [ ] 基于现有需求做一些实际程序, 尤其是小规模/与中文处理有关/不仅限于IT领域的 (参考 #19 #41 ), 如
  - [x] [五笔码整理编辑器](https://www.v2ex.com/t/490269)
- [ ] 试用各种中文编程工具
  - [ ] [WinDev中文版](http://cn.windev.com/)
  - [ ] [口袋编程(iOS)](https://itunes.apple.com/cn/app/%E5%8F%A3%E8%A2%8B%E5%BC%95%E6%93%8E-%E5%88%9B%E5%BB%BA%E7%A8%8B%E5%BA%8F%E8%AE%BE%E8%AE%A1%E5%8E%9F%E5%9E%8B/id1415607268)
- [ ] 编译器相关
  - [ ] vscode下TypeScript可设置为[中文反馈编译信息](
https://www.zhihu.com/pin/1062349662463381504) [VS下貌似早已支持](https://social.msdn.microsoft.com/Forums/vstudio/en-US/f99d14b9-c889-419f-9252-835bec7c7393/avoid-debug-and-compile-errors-localization?forum=vssetup)
- [ ] IDE问题
  - [ ] Eclipse: 拼音输入后, ctrl-z会从拼音开始回退. 比如"换算", 会从`huan's`开始而不是中文字符.
  - [ ] 听说VS下的智能感知功能对中文命名无效, 需要调研一下
- [ ] 开发中文API, 类似[英汉词典](https://zhuanlan.zhihu.com/p/43977821)
  - [ ] [新华词典](https://github.com/pwxcoo/chinese-xinhua)
  - [ ] [正则表达式](https://www.v2ex.com/t/540910#r_6977210)
  - [ ] cron表达式, 参考[cron-utils](https://github.com/jmrozanec/cron-utils)
- [ ] 为新的自媒体频道开发相关应用("用中文编程"微信公众号和今日头条)
  - [ ] 微信小程序

希望大家多多建议新主题, 更欢迎投稿!

**Comment by jeffreybaoshenlee** [comment]
看到專欄了，前排支持～

**Comment by nobodxbodon** [comment]
多谢! 刚刚写了[一篇](https://zhuanlan.zhihu.com/p/30882225), 希望说明一下专栏的目标. 如有疏漏和不妥之处请多指摘!

**Comment by nobodxbodon** [comment]
诚征编辑(能管理投稿, 调整作者权限, 发布文章)和作者(能发布文章).

**Comment by nobodxbodon** [comment]
@jeffreybaoshenlee @swizl 冒昧邀请二位成为专栏编辑. 如有顾虑请知乎私信联系~

**Comment by nobodxbodon** [comment]
不好意思忘了更新. 这几个月大多的个人实践活动都发在了知乎专栏文章, 不知不觉也积累了50多篇, 也多谢 @swizl 和 @bhuztez 的加持. 总目录在[中文编程专栏目录, 初衷和希冀](https://zhuanlan.zhihu.com/c_140193266)后部(最近十几天的文章链接马上会加入). 欢迎各位批评指点!

**Comment by nobodxbodon** [comment]
[中文代码示例视频演示Python入门教程第三章 简介Python](https://zhuanlan.zhihu.com/p/37674681)之前用了B站, 刚开始把视频传到[youtube](https://www.youtube.com/watch?v=gczemTc4y1c&index=1&list=PLa_0j6lBR_F7h-Fin3IY2YPSADC1V-CV3)
今后如有新专栏文章, 会尽量在此通告.

**Comment by absente** [comment]
想加入。zhihu.com/people/101010

**Comment by nobodxbodon** [comment]
新文章:
[中文代码示例视频演示Python入门教程第四章 控制流](https://zhuanlan.zhihu.com/p/38282172)
[中文代码示例视频演示Python入门第五章 数据结构](https://zhuanlan.zhihu.com/p/38324987)
[解谜计算机科学第一章示例汉化尝试](https://zhuanlan.zhihu.com/p/38514754)
["西游记"主题Python入门示例尝试-数据结构 5.1-5.1.2](https://zhuanlan.zhihu.com/p/38653108)
[为Chrome和火狐浏览器编写扩展](http://zhuanlan.zhihu.com/p/39425449)
[万马齐喑究可哀-中文编程的又一波"讨论"](https://zhuanlan.zhihu.com/p/40068451)
[最近一波对中文编程(包括中文命名)的攻势](https://zhuanlan.zhihu.com/p/40099718)
[在代码中进行中文命名(类/变量/方法等)的优势](https://zhuanlan.zhihu.com/p/40098652)
[Z中文编程创新突破1-把Z语句分析生成C#函数](https://zhuanlan.zhihu.com/p/24153393)
[中文编程Ｚ语言设计思想](https://zhuanlan.zhihu.com/p/40356993)
[Z语言实现基本原理](https://zhuanlan.zhihu.com/p/40523508)
[又见套路:如果计算机是用中文编程,你能成为计算机编程专家吗？](https://zhuanlan.zhihu.com/p/40611223)
[对DLL库中的接口进行中文命名](https://zhuanlan.zhihu.com/p/40833425)
[中文编程讨论组一岁了](https://zhuanlan.zhihu.com/p/41129712)
[中文代码示例之Python-如何遍历字典](https://zhuanlan.zhihu.com/p/41252090)
[re:从中美文化差异看编程的发展方向](https://zhuanlan.zhihu.com/p/40295586)
[在Office的VBA代码里中文命名](https://zhuanlan.zhihu.com/p/41432021)
[中文代码示例之Spring Boot 2.0.3问好](https://zhuanlan.zhihu.com/p/41836608)
[中文编程讨论组(Github)社区守则一周年修订](https://zhuanlan.zhihu.com/p/41914179)
[Head First OO分析设计一书略读与例子中文化](https://zhuanlan.zhihu.com/p/41920600)

接下去个人打算以两个方向为主: 
- [入门教程设计](https://github.com/program-in-chinese/overview/issues/5#issuecomment-412436818)
- [术语词典API](https://github.com/program-in-chinese/overview/issues/54#issuecomment-411551138)

**Comment by nobodxbodon** [comment]
新文章:
[中文代码之Spring Boot实现简单REST服务](https://zhuanlan.zhihu.com/p/42100391)
[中文代码之Spring Boot添加基本日志](https://zhuanlan.zhihu.com/p/42247945)
[[转载]手机编程与AIDE](https://zhuanlan.zhihu.com/p/42390497)
[在WSL上编译OpenJDK10](https://zhuanlan.zhihu.com/p/42410610)
[改造JAVA，给OpenJDK10添加中文关键词](https://zhuanlan.zhihu.com/p/42442463)
[中文代码之Spring Boot集成H2内存数据库](https://zhuanlan.zhihu.com/p/42540265)

**Comment by nobodxbodon** [comment]
新文章:
[中文关键词替换体验页面原型](http://zhuanlan.zhihu.com/p/42634693)
[为中文API的简繁转换库添加迟到的持续集成](http://zhuanlan.zhihu.com/p/42729304)
[中文代码之Spring Boot对H2数据库简单查询](http://zhuanlan.zhihu.com/p/42863835)
[使用JDT核心库解析JDK源码后初步分析API命名](http://zhuanlan.zhihu.com/p/43111638)
[浏览器插件实现GitHub代码翻译原型演示](https://zhuanlan.zhihu.com/p/43304088) @swizl 思路借鉴了你之前的https://github.com/program-in-chinese/overview/issues/59#issuecomment-411272880

**Comment by swizl** [comment]
@nobodxbodon 最近在搞node.js，里面v8添加中文关键字看样子不难。弄好之后，后端开发也可以有一个中文环境了。后面希望能找到一个精简版的chromium源码，搞出一个支持中文关键字的浏览器。

**Comment by nobodxbodon** [comment]
@swizl 
> 后面希望能找到一个精简版的chromium源码

可以考虑这位裁剪的版本: [miniblink](https://zhuanlan.zhihu.com/p/22663686)

**Comment by swizl** [comment]
@nobodxbodon 看了一下那个作者的文章，不知道 miniblink 只是一个内核模块，还是一个较完整的浏览器。他后面集成了node.js挺有意思的。electron这个框架也挺有意思的，有时间，也玩玩。

**Comment by nobodxbodon** [comment]
新文章:
[Java实现英汉词典API初版发布在Maven](http://zhuanlan.zhihu.com/p/43977821) 源于 https://github.com/program-in-chinese/overview/issues/88
接下去在开发https://github.com/program-in-chinese/overview/issues/86 的原型过程中, 逐步完善此API, 并同时逐步积累[术语词典](https://github.com/program-in-chinese/overview/issues/85).

**Comment by nobodxbodon** [comment]
新文章:
[用Python3+tkinter开发简单图形界面程序](https://zhuanlan.zhihu.com/p/45597251)

@swizl 请问对[源码翻译项目](https://zhuanlan.zhihu.com/p/45236358)有什么建议吗?

**Comment by swizl** [comment]
@nobodxbodon 想了一下做成对单个源文件翻译的工具就好了。遍历文件夹用shell等工具处理就可以了。但是得保存词条表。流程大概是：先在词条表中查找，有的话，直接用，以保证整个工程翻译的一致性。没有的话，调用翻译接口，使用返回结果，并保存在词条表中。

**Comment by nobodxbodon** [comment]
新文章:
[[日常]用Python读取word文档中的表格并比较](https://zhuanlan.zhihu.com/p/45997055)
[用elixir实现一个简单的中文语句解析](https://zhuanlan.zhihu.com/p/46030123)
[Java源码英翻中进展-内测上线](https://zhuanlan.zhihu.com/p/46207832)
[在浏览器插件中读取JSON资源文件](https://zhuanlan.zhihu.com/p/46452691)
[浏览器插件-离线英汉词典](https://zhuanlan.zhihu.com/p/46640311)

**Comment by nobodxbodon** [comment]
时间倒序:
[专栏一岁了-我为什么投身于普及用中文编程](http://zhuanlan.zhihu.com/p/48272342) 以及[v2ex转帖](https://www.v2ex.com/t/503610)
[在线代码离线翻译Chrome插件"一马"v0.0.8](http://zhuanlan.zhihu.com/p/48120706)
[浏览器插件-离线英汉词典 0.0.7](http://zhuanlan.zhihu.com/p/48116424)
[初步尝试将传统学科的内容程序/数据化](http://zhuanlan.zhihu.com/p/47807062)
[前端会用标签模板（Tagged Templates）就能当股神](http://zhuanlan.zhihu.com/p/36426258)
[Chrome插件实现GitHub代码离线翻译v0.0.4](http://zhuanlan.zhihu.com/p/47215777)
[它山之石-日本推广编程中使用日语命名的渊源](https://zhuanlan.zhihu.com/p/47128031)
[首次发现在例程中使用日语命名的编程书籍](https://zhuanlan.zhihu.com/p/47127716)
[Chrome插件实现GitHub代码翻译v0.0.3](https://zhuanlan.zhihu.com/p/47071729)

**Comment by nobodxbodon** [comment]
| 知乎文章 | v2ex转帖 | 
| ------------- | ------------- |
| [专栏全年主题合辑-代码中文命名相关实践](https://zhuanlan.zhihu.com/p/49295556) | [链接](https://www.v2ex.com/t/506755#reply37) |
| [专栏全年主题合辑-中文编程语言开发尝试](https://zhuanlan.zhihu.com/p/49190145) | [链接](https://www.v2ex.com/t/506501#reply23) |
| [VS Code英汉词典插件v0.0.4-驼峰下划线命名](https://zhuanlan.zhihu.com/p/49133480) |  |
| [用中文编程-专栏初衷回顾](https://zhuanlan.zhihu.com/p/48397938) |  |
| [Visual Studio Code插件-英汉词典初版发布](https://zhuanlan.zhihu.com/p/48791726) |  |
| [在线代码离线翻译Chrome插件"一马"v0.0.14](https://zhuanlan.zhihu.com/p/48597668) | |
| [在代码中进行中文命名实践的短期目标](https://zhuanlan.zhihu.com/p/48396253)   | [链接](https://www.v2ex.com/t/503995#reply17) |

**Comment by nobodxbodon** [comment]
| 知乎文章 | v2ex转帖 | 
| ------------- | ------------- |
| [中文编程,最精致的python访客登记系统实例项目,微信机器人不再只当人工智障------03](https://zhuanlan.zhihu.com/p/51097325) | [链接](https://www.v2ex.com/t/512550) |
| [中文编程,最精致的python访客登记系统实例项目,微信机器人不再只当人工智障------02](https://zhuanlan.zhihu.com/p/51014598) | |
| [中文编程,最精致的python访客登记系统实例项目,微信机器人不再只当人工智障------01](https://zhuanlan.zhihu.com/p/50902870) |  |
| [中文代码示例之Programming in Scala笔记第七八章](https://zhuanlan.zhihu.com/p/50979126) |  |
| [手工翻译Vue.js源码:尝试重命名标识符与文本](https://zhuanlan.zhihu.com/p/50726829) | [链接](https://www.v2ex.com/t/510996#reply25) |
| [手工翻译Vue.js源码第一步:14个文件重命名](https://zhuanlan.zhihu.com/p/50507506) | [链接](https://www.v2ex.com/t/510083#reply11) |
| [中文代码示例之Programming in Scala笔记第四五六章](https://zhuanlan.zhihu.com/p/50093833) | |
| [中文代码示例之Programming in Scala学习笔记第二三章](https://zhuanlan.zhihu.com/p/49707717)   | |

**Comment by nobodxbodon** [comment]
| 知乎文章 | v2ex转帖 | 
| ------------- | ------------- |
| [VS Code英汉词典插件v0.0.7-尝试词性搭配](https://zhuanlan.zhihu.com/p/51525136) | |
| [中文编程,最精致的python访客登记系统实例项目,微信机器人不再只当人工智障------06](https://zhuanlan.zhihu.com/p/51382282) | [链接](https://www.v2ex.com/t/514163#reply0) |
| [中文编程，用 Python 编写小说网站爬虫](https://zhuanlan.zhihu.com/p/51309019) | [链接](https://www.v2ex.com/t/513438#reply7) |
| [中文编程,最精致的python访客登记系统实例项目,微信机器人不再只当人工智障------05](https://zhuanlan.zhihu.com/p/51276692) | |
| [VS Code英汉词典插件v0.0.6-改为TS实现, 加测试](https://zhuanlan.zhihu.com/p/51243255) | |
| [中文编程,最精致的python访客登记系统实例项目,微信机器人不再只当人工智障------04](https://zhuanlan.zhihu.com/p/51184689) |  |

**Comment by nobodxbodon** [comment]
| 知乎文章 | v2ex转帖 | 
| ------------- | ------------- |
| [用python编写控制网络设备的自动化脚本1：框架设计](https://zhuanlan.zhihu.com/p/53641620) | |
| [[转载] 做煎饼果子的N种方式——From Sequential to Reactive](https://zhuanlan.zhihu.com/p/53416369) | |
| [VS Code英汉词典v0.0.8: 批量翻译文件部分命名](https://zhuanlan.zhihu.com/p/53288297) | |
| [专栏关注人少,我用爬虫做知乎数据分析---04](https://zhuanlan.zhihu.com/p/53261378) | |
| [在国内原创开源项目中使用中文命名的意义与方式](https://zhuanlan.zhihu.com/p/53050766) | [链接0](https://www.v2ex.com/t/518452#reply193) |
| [专栏关注人少,我用爬虫做知乎数据分析---03](https://zhuanlan.zhihu.com/p/53035007) | |
| [专栏关注人少,我用爬虫做知乎数据分析---02](https://zhuanlan.zhihu.com/p/52984841) | |
| [专栏关注人少,我用爬虫做知乎数据分析---01](https://zhuanlan.zhihu.com/p/52969986) | |
| [VS Code英汉词典进化效果演示: 翻译文件所有命名](https://zhuanlan.zhihu.com/p/52543477) | |
| [JavaScript实现ZLOGO: 前进方向和速度](https://zhuanlan.zhihu.com/p/52434775) | |
| [Scala疑似中文命名问题后续](https://zhuanlan.zhihu.com/p/52114604) | |
| [疑似bug_中文代码示例之Programming in Scala笔记第九十章](https://zhuanlan.zhihu.com/p/51998712) | [链接](https://www.v2ex.com/t/513438#reply7) |
| [中文编程,最精致的python访客登记系统实例项目,微信机器人不再只当人工智障---08](https://zhuanlan.zhihu.com/p/51902838) | |
| [中文编程,最精致的python访客登记系统实例项目,微信机器人不再只当人工智障------07](https://zhuanlan.zhihu.com/p/51771041) | [链接](https://www.v2ex.com/t/515200#reply12) |

**Comment by nobodxbodon** [comment]
[中文编程,python控制Excel实现跨文件复制Sheet.](https://zhuanlan.zhihu.com/p/54847656)
[[日常]mov文件转换为gif](https://zhuanlan.zhihu.com/p/54832362)

**Comment by nobodxbodon** [comment]
[程序员面试时用中文命名写白板代码的好处](https://zhuanlan.zhihu.com/p/56271111) [v2讨论链接](https://www.v2ex.com/t/533386#reply19)
[Librian: 简明强大的Galgame引擎](https://zhuanlan.zhihu.com/p/56173201)
[用python编写控制网络设备的自动化脚本2：显示](https://zhuanlan.zhihu.com/p/56108138)
[VS Code创建自定义Python代码片段](https://zhuanlan.zhihu.com/p/56035257)
[[日常]Beyond的歌里最多是"唏嘘"吗? - Python分词+词频](https://zhuanlan.zhihu.com/p/55949416)
[谁说不能用中文写代码？](https://zhuanlan.zhihu.com/p/55463326)
[JavaScript实现ZLOGO: 性能改进](https://zhuanlan.zhihu.com/p/55626846)
[JavaScript实现ZLOGO: 界面改进与速度可调](https://zhuanlan.zhihu.com/p/55359648)
[中文编程,python控制Excel实现跨文件复制Sheet.](https://zhuanlan.zhihu.com/p/54847656)

**Comment by nobodxbodon** [comment]
由前到后:
[扩展Python控制台实现中文反馈信息](https://zhuanlan.zhihu.com/p/56411693)
[1992年日本对母语编程的可读性比较实验](https://zhuanlan.zhihu.com/p/56756996)
[用python编写控制网络设备的自动化脚本3：启动](https://zhuanlan.zhihu.com/p/56833809)
[扩展Python控制台实现中文反馈信息之二-正则替换](https://zhuanlan.zhihu.com/p/57079638)
[在PyPI测试平台发布Python包](https://zhuanlan.zhihu.com/p/57211755)
[中文代码示例之Electron桌面应用开发初体验](https://zhuanlan.zhihu.com/p/58807431)
[中文代码示例之NW.js桌面应用开发初体验](https://zhuanlan.zhihu.com/p/58808639)
[转载: 中文輸進去，程式出得來，開發者發大財 -LingaScript:中文化TypeScript](https://zhuanlan.zhihu.com/p/59308226)
[为《 两周自制脚本语言 》添加中文测试代码](https://zhuanlan.zhihu.com/p/59247625)
[将《 两周自制脚本语言 》测试中使用的接口中文化](https://zhuanlan.zhihu.com/p/59418720)
[用python编写控制网络设备的自动化脚本4：接口](https://zhuanlan.zhihu.com/p/59428605)
[5分钟入门LingaScript-尝鲜中文版TypeScript](https://zhuanlan.zhihu.com/p/59426216)
[重拾《 两周自制脚本语言 》- 支持中文标识符](https://zhuanlan.zhihu.com/p/59491495)
[重拾《 两周自制脚本语言 》- 中文关键字与原生函数](https://zhuanlan.zhihu.com/p/59554958)
[重拾《 两周自制脚本语言 》- Eclipse插件实现语法高亮](https://zhuanlan.zhihu.com/p/59890614)
[演示Eclipse插件实现代码提示和补全](https://zhuanlan.zhihu.com/p/60060945)
[破解一个卸载码生成算法的过程](https://zhuanlan.zhihu.com/p/60211016)
[Java实现"命令式"简易文本编辑器原型](https://zhuanlan.zhihu.com/p/60946984)
[Java实现文本编辑时基于拼音输入的补全原型](https://zhuanlan.zhihu.com/p/61254238)
[为Jekyll+GitHub Pages添加全文搜索功能](https://zhuanlan.zhihu.com/p/61788902)
[公众号简单爬虫--把公众号文章全部转载到网站（一）](https://zhuanlan.zhihu.com/p/62000663)
[公众号简单爬虫--把公众号文章全部转载到网站（二）](https://zhuanlan.zhihu.com/p/62243426)
[公众号简单爬虫--把公众号文章全部转载到网站（三）](https://zhuanlan.zhihu.com/p/63004624)
[【Librian】中文galgame剧本格式解析原理](https://zhuanlan.zhihu.com/p/63033719)
[用python编写控制网络设备的自动化脚本5：访问控制列表](https://zhuanlan.zhihu.com/p/63076652)
[中文命名之Hibernate 4+MySQL演示](https://zhuanlan.zhihu.com/p/63518209)
["用中文编程"微信公众号和今日头条开通, 其他各交流渠道小结](https://zhuanlan.zhihu.com/p/64079707)
[尝试扩展Python控制台添加中文关键字](https://zhuanlan.zhihu.com/p/65258736)
[转：（中文命名）UML类图新手入门级介绍](https://zhuanlan.zhihu.com/p/65391563)
[中文命名之Hibernate 5演示 - 使用注解(annotation)而非xml定义映射](https://zhuanlan.zhihu.com/p/65784218)

**Comment by nobodxbodon** [comment]
由前到后：
[用python编写控制网络设备的自动化脚本6：框架设计2](https://zhuanlan.zhihu.com/p/67650697)
[从立创EDA，Gratipay看中文编程开发环境和推广运营的一个趋势](https://zhuanlan.zhihu.com/p/69883126)
[中文代码之Django官方入门：建立模型](https://zhuanlan.zhihu.com/p/72170870)
[用JS Search实现客户端JSON内容索引和搜索](https://zhuanlan.zhihu.com/p/75985099)
[[自己动手, 丰衣足食] Python脚本找到大垃圾文件(夹)](https://zhuanlan.zhihu.com/p/78914328)
[手工翻译方舟编译器源码:尝试重命名标识符与文本](https://zhuanlan.zhihu.com/p/81450947)
[尝试方舟编译器下对Java中标识符中文命名](https://zhuanlan.zhihu.com/p/81700604)
[手工翻译方舟编译器源码: IR相关节点类](https://zhuanlan.zhihu.com/p/81979178)
[用python编写控制网络设备的自动化脚本7：跳板（远程登录）](https://zhuanlan.zhihu.com/p/83475460)
[中文编程语言及编程思维](https://zhuanlan.zhihu.com/p/58165734)
[既然开发新中文编程语言离不开API, 何不从开发API开始呢? 更进一步, 何不从例程开始呢?](https://zhuanlan.zhihu.com/p/85081589)
[尝试自动批量翻译方舟编译器源码中的标识符](https://zhuanlan.zhihu.com/p/85085837)
[自制TTS引擎第0.01步-Python实现拼接单字wav文件](https://zhuanlan.zhihu.com/p/85486162)
[自制TTS引擎第0.02步-单字拼音化, 从Excel表格用Python提取拼音表](https://zhuanlan.zhihu.com/p/85601740)
[(多图)火热出炉的大疆机甲大师教育机器人开箱组装小记](https://zhuanlan.zhihu.com/p/86316396)
[[日常] Python缩小jpg图片尺寸](https://zhuanlan.zhihu.com/p/86571051)
[大疆机甲大师Python开发: 中文命名变量初尝试](https://zhuanlan.zhihu.com/p/86686589)
[大疆机甲大师Python开发: API中文化初尝试](https://zhuanlan.zhihu.com/p/86692696)
[【Night Beam】去除文本马赛克的随机算法！](https://zhuanlan.zhihu.com/p/86866269)
[大疆机甲大师Python开发: 两只老虎](https://zhuanlan.zhihu.com/p/87072890)
[大疆机甲大师教育机器人Python API中文化之一：枪亮枪暗](https://zhuanlan.zhihu.com/p/87816006)
[大疆机甲大师教育机器人Python API中文化之二：LED闪烁](https://zhuanlan.zhihu.com/p/87999357)
[大疆机甲大师教育机器人Python API中文化之三：底盘灯效](https://zhuanlan.zhihu.com/p/87999734)
[大疆机甲大师教育机器人Python API中文化之四五：云台灯效，指定序号](https://zhuanlan.zhihu.com/p/88215643)
[大疆机甲大师教育机器人Python API中文化之六：关灯](https://zhuanlan.zhihu.com/p/88389200)
[大疆机甲大师Python API之七：做个闹钟](https://zhuanlan.zhihu.com/p/88558581)
[潜力需要分享来加速挖掘：大疆机甲大师Python开发两周感想之一](https://zhuanlan.zhihu.com/p/88559004)
[[意外走向] 大疆机甲大师Python API之八：计时 -- 为性能测试展开1000次循环](https://zhuanlan.zhihu.com/p/88964199)
[【小惊吓】大疆机甲大师Python API之九：整机控制模式](https://zhuanlan.zhihu.com/p/89182664)
[【日常】五行Python代码由png图片生成gif文件](https://zhuanlan.zhihu.com/p/89394860)
[大疆机甲大师Python API之十：程序运行时间](https://zhuanlan.zhihu.com/p/89626066)
[【日常】Python读取解析xml文件，顺便转换为大疆机甲大师可以演奏的乐谱](https://zhuanlan.zhihu.com/p/89736491)
[【巧妇难为无米之炊】为机甲大师从MusicXML提取乐谱之卡农](https://zhuanlan.zhihu.com/p/90142676)
[大疆机甲大师Python API之十一：用上电时间实测电池放电曲线](https://zhuanlan.zhihu.com/p/90395027)
[大疆机甲大师Python API之十二：识别郭德纲于谦](https://zhuanlan.zhihu.com/p/90607858)
[“中文编程”知乎专栏两岁了——山雨欲来风满楼](https://zhuanlan.zhihu.com/p/91353256)

**Comment by nobodxbodon** [comment]
知乎专栏于几年前转为个人名下。
建议在发表相关内容时添加 [“中文编程”话题](https://github.com/program-in-chinese/overview/issues/167)。

**Comment by FansinZhao** [comment]
我已收到您的邮件！谢谢
